### ISSUE TITLE
Question: How to deploy Opik using Helm without using CRD?

### ISSUE THREAD

**Issue by lryan599** [comet-ml/opik#1335]
Hi,

I really like Opik and want to use it in actual production. However, due to permission limitations, I'm unable to install ClickHouse using the method of Custom Resource Definition (CRD). I'm new to Helm and I don't know how to modify the chart template. Are there any other templates that can help me deploy Opik using Helm without the need to use CRD like ClickHouseInstallation?

I found this https://bitnami.com/stack/clickhouse/helm, can it solve my problem?

Some suggestions would also be extremely helpful to me. Thank you very much!

**Comment by alexkuzmik** [comment]
Hi @lryan599! You can install Clickhouse in any way you want and disable it in the chart. Here is an example with configuration snippet.
```
...
opik:
  component:
    backend:
      ...
      env:
        ANALYTICS_DB_MIGRATIONS_URL: "jdbc:clickhouse://<YOUR CLICKHOUSE HOST>:8123"
        ANALYTICS_DB_HOST: "<YOUR CLICKHOUSE HOST>"
        ANALYTICS_DB_DATABASE_NAME: "opik"  
      initContainers:
      - name: wait-for-clickhouse-service
        image: stefanevinance/wait-for-200
        env:
          - name: URL
            value: http://<YOUR CLICKHOUSE HOST>:8123
...
  clickhouse:
    enabled: false
...
```

We'll add this instruction to our readme section.

FYI @liyaka
