### ISSUE TITLE
[FR]: Include whole request config (temp, top_p, etc.) for openAI client trace

### ISSUE THREAD

**Issue by gustavhartz** [comet-ml/opik#1447]
### Proposal summary

Would be nice with the full openai configuration in visible in the trace calls
Current:
![Image](https://github.com/user-attachments/assets/bc75c17c-9a0f-436f-a82f-00f52f674a11)
Better:
![Image](https://github.com/user-attachments/assets/91f7f4c2-6abf-4479-b86a-7bf4618a8103)

### Motivation

**What problem are you trying to solve?:**: save time on looking into configurations in code
**How are you currently solving this problem?:** easier traceability and understanding of model performance 
**What are the benefits of this feature?**: Saves time from looking at config in code

**Comment by alexkuzmik** [comment]
Hi @gustavhartz! We do log this information, it can be seen in span's metadata tab. Do I understand it right, you are aware of that but still would like to be able to see all the input parameters in the span's input tab?

**Comment by gustavhartz** [comment]
hi @alexkuzmik 

In the spans metadata tab i only see the info below. Am i missing something? I don't specify it explicitly, so is it because you don't log the default value?
```yml
usage:
  completion_tokens: 224
  prompt_tokens: 1934
  total_tokens: 2158
  completion_tokens_details:
    accepted_prediction_tokens: 0
    audio_tokens: 0
    reasoning_tokens: 0
    rejected_prediction_tokens: 0
  prompt_tokens_details:
    audio_tokens: 0
    cached_tokens: 0
model: gpt-4o-2024-08-06
response_format: <class 'xxx'>
created_from: openai
type: openai_chat
id: chatcmpl-xxx
created: 1741081925
object: chat.completion
service_tier: null
system_fingerprint: xxx
prompt_filter_results:
  - prompt_index: 0
    content_filter_results:
      hate:
        filtered: false
        severity: safe
      jailbreak:
        filtered: false
        detected: false
      self_harm:
        filtered: false
        severity: safe
      sexual:
        filtered: false
        severity: safe
      violence:
        filtered: false
        severity: safe
```

and 
`completion_tokens: 224
prompt_tokens: 1934
total_tokens: 2158`
