### ISSUE TITLE
[Question]: Do we need to add `waitForMysql` to the backend component in helm chart?

### ISSUE THREAD

**Issue by lryan599** [comet-ml/opik#2364]
`waitForClickhouse` waits for Clickhouse initialization to complete, but there is no `waitForMysql` to wait for Mysql initialization to complete, which may result in the following error when using `helm install` directly:

![Image](https://github.com/user-attachments/assets/3c0027b9-2aa9-466a-895d-1a4d1a2bc7fd)

As a result, the `opik-backend` deployment crashes and restarts several times until Mysql is able to function properly.

**Comment by liyaka** [comment]
Hi @lryan599, thank you for bringing it up.
Till now, in all various installations of Opik, tested with internal MySQL and RDS, we didn't need to "wait" for MySQL to come up, since no initial procedures are running, and it is available very fast.
If you need to add an initContainer for your case, you have this option to do it in your values:
```
component:
  backend:
    ...
    initContainers:          
    - name: wait-for-mysql-service
      image: ...
      command: ...
      args:  ...
```
