### ISSUE TITLE
[Bug]: Helm Chart Ingress doesn't specify a secretName for TLS

### ISSUE THREAD

**Issue by knechtionscoding** [comet-ml/opik#2366]
### What component(s) are affected?

- [ ] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.7.29

### Describe the problem

When using a cert-manager to manage certificates inside the k8s cluster you need to specify the secretName as part of the ingress object under `spec.tls[0].secretname`. In order to have a cert provisioned I have to currently provide a patch:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opik-frontend
  namespace: opik
spec:
  tls:
    - hosts:
        - <host>
      secretName: opik-frontend-tls
```
