### ISSUE TITLE
[FR]: Support PostgresSql as a state DB

### ISSUE THREAD

**Issue by mck-star-yar** [comet-ml/opik#2402]
### Proposal summary

We need to expose DB drivers' (such as MySQL, PostgreSQL, etc.) dependencies via container variables to be able to do something like this:

```yml
  backend:
    image: ghcr.io/comet-ml/opik/opik-backend:${OPIK_VERSION:-latest}
    environment:
      STATE_DB_PROTOCOL: "jdbc:postgresql://"
      EXTRA_DEPENDENCIES:
        - org.postgresql: 42.7.6
```

### Motivation

In our tech stack we use postgres as a rel-db. We want opik to use that instead of mysql. We have couple variables exposed from the container to help us do that:

desired state
```yml
      STATE_DB_PROTOCOL: "jdbc:postgresql://"
      STATE_DB_URL: "postgres:5432/core"
      STATE_DB_DATABASE_NAME: core
      STATE_DB_DRIVER_CLASS : org.postgresql.Driver
      STATE_DB_USER: postgres
      STATE_DB_PASS: postgres
```

However server doesn't have postgresql driver to connect to the specified db. We need to add that to pom.xml and then rebuild container. This adds maintenance and source code ownership complexity.
